<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=5">



    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">

    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#00a300">
    <meta name="theme-color" content="#ffffff">


    <meta name="keywords"
        content="Be, Local, Madeira, madeira, island, canyoning, canionismo, caminhada, hiking, adventure, experience, aventura, coasteering, hiking, caminhada, passeio, activity, atividade, bicicleta">
    <meta name="author" content="Rúben Freitas">
    <meta name="description"
        content="Be Local Madeira aims to provide the most dynamic and genuine experiences the Island has to offer. With us you will experience nature at its most stunning, creating adventures that will stay with you forever!">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link
        href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;500;700&family=Russo+One&display=swap&family=Merienda+One&family=Playfair+Display:ital,wght@0,500;1,900&display=swap"
        rel="stylesheet">

    <title>Be Local Madeira</title>

    <script type="application/ld+json">
        {"@context" : "http://schema.org",
         "@type" : "Organization",  
          "name" : "Be Local Madeira",
          "url" : "https://belocalmadeira.com/", 
          "logo": "https://belocalmadeira.com/images/new_background_1920.webp" }
    </script>

</head>

<style>
    html,
    body,
    #index {
        height: 100%;
        font-family: 'IBM Plex Sans Arabic', sans-serif;
        scroll-behavior: smooth;
    }

    .full-page-loader {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        width: 100vw;
        background: #344A35;
        background: url("/image/new_background_blur.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        box-sizing: border-box;
        overflow: hidden;
        animation-delay: 5s;
    }

    body {
        margin: 0;
        position: relative;
    }

    .logo-animation {
        -webkit-animation: disappear .6s forwards;
        animation: disappear .6s forwards;
        animation-delay: 4.5s;
        width: 150px;
    }

    .menu-dropdown {
        right: 0;
        top: 80px !important;
        padding: 20px 30px;
    }

    .ant-dropdown {
        position: fixed !important;
    }

    @-webkit-keyframes disappear {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }


    /***************************************************
    * Generated by SVG Artista on 7/6/2022, 11:41:31 AM
    * MIT license (https://opensource.org/licenses/MIT)
    * W. https://svgartista.net
    **************************************************/

    @keyframes animate-svg-fill-1 {
        0% {
            fill: transparent;
        }

        100% {
            fill: rgb(255, 255, 255);
        }
    }

    .svg-elem-36 {
        animation: animate-svg-fill-1 0.4s ease 0.2s both;
    }

    .svg-elem-37 {
        animation: animate-svg-fill-1 0.4s ease 0.3s both;
    }

    .svg-elem-38 {
        animation: animate-svg-fill-1 0.4s ease 0.4s both;
    }

    .svg-elem-39 {
        animation: animate-svg-fill-1 0.4s ease 0.5s both;
    }

    .svg-elem-40 {
        animation: animate-svg-fill-1 0.4s ease 0.6s both;
    }

    .svg-elem-41 {
        animation: animate-svg-fill-1 0.4s ease 0.7s both;
    }

    .svg-elem-42 {
        animation: animate-svg-fill-1 0.4s ease 0.8s both;
    }

    .svg-elem-43 {
        animation: animate-svg-fill-1 0.4s ease 0.9s both;
    }

    .svg-elem-44 {
        animation: animate-svg-fill-1 0.4s ease 1s both;
    }

    .svg-elem-45 {
        animation: animate-svg-fill-1 0.4s ease 1.1s both;
    }

    .svg-elem-46 {
        animation: animate-svg-fill-1 0.4s ease 1.2s both;
    }

    .svg-elem-47 {
        animation: animate-svg-fill-1 0.4s ease 1.3s both;
    }

    .svg-elem-48 {
        animation: animate-svg-fill-1 0.4s ease 1.4s both;
    }

    .svg-elem-49 {
        animation: animate-svg-fill-1 0.4s ease 1.5s both;
    }

    .svg-elem-50 {
        animation: animate-svg-fill-1 0.4s ease 1.6s both;
    }

    .svg-elem-51 {
        animation: animate-svg-fill-1 0.4s ease 1.7s both;
    }

    .svg-elem-52 {
        animation: animate-svg-fill-1 0.4s ease 1.8s both;
    }

    .svg-elem-53 {
        animation: animate-svg-fill-1 0.4s ease 1.9s both;
    }

    .svg-elem-54 {
        animation: animate-svg-fill-1 0.4s ease 2s both;
    }

    .svg-elem-55 {
        animation: animate-svg-fill-1 0.4s ease 2.1s both;
    }

    .svg-elem-56 {
        animation: animate-svg-fill-1 0.4s ease 2.2s both;
    }

    .svg-elem-57 {
        animation: animate-svg-fill-1 0.4s ease 2.3s both;
    }

    .svg-elem-58 {
        animation: animate-svg-fill-1 0.4s ease 2.4s both;
    }

    .svg-elem-59 {
        animation: animate-svg-fill-1 0.4s ease 2.5s both;
    }

    .svg-elem-60 {
        animation: animate-svg-fill-1 0.4s ease 2.6s both;
    }

    .svg-elem-61 {
        animation: animate-svg-fill-1 0.4s ease 2.7s both;
    }

    .svg-elem-62 {
        animation: animate-svg-fill-1 0.4s ease 2.8s both;
    }

    .svg-elem-63 {
        animation: animate-svg-fill-1 0.4s ease 2.9s both;
    }

    .svg-elem-64 {
        animation: animate-svg-fill-1 0.4s ease 3s both;
    }

    .svg-elem-65 {
        animation: animate-svg-fill-1 0.4s ease 3.1s both;
    }

    .svg-elem-66 {
        animation: animate-svg-fill-1 0.4s ease 3.2s both;
    }

    .svg-elem-67 {
        animation: animate-svg-fill-1 0.4s ease 3.3s both;
    }

    .svg-elem-68 {
        animation: animate-svg-fill-1 0.4s ease 3.4s both;
    }

    .svg-elem-69 {
        animation: animate-svg-fill-1 0.4s ease 3.5s both;
    }

    .svg-elem-70 {
        animation: animate-svg-fill-1 0.4s ease 3.6s both;
    }

    .svg-elem-71 {
        animation: animate-svg-fill-1 0.4s ease 3.7s both;
    }

    .svg-elem-72 {
        animation: animate-svg-fill-1 0.4s ease 3.8s both;
    }

    .svg-elem-73 {
        animation: animate-svg-fill-1 0.4s ease 3.9s both;
    }

    .svg-elem-74 {
        animation: animate-svg-fill-1 0.4s ease 4s both;
    }

    .svg-elem-75 {
        animation: animate-svg-fill-1 0.4s ease 4.1s both;
    }

    .svg-elem-76 {
        animation: animate-svg-fill-1 0.4s ease 4.2s both;
    }
</style>



<body>
    <div id="index">
        <div class="full-page-loader">
            <svg class="logo-animation" version="1.1" id="svg2" width="391.54266357421875" height="334.28265380859375"
                viewBox="0 0 391.54265 334.28266" sodipodi:docname="belocal.svg"
                inkscape:version="1.2 (1:1.2+202206011327+fc4e4096c5)"
                xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
                xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns="http://www.w3.org/2000/svg"
                xmlns:svg="http://www.w3.org/2000/svg">
                <defs id="defs6"></defs>

                <g id="g10" inkscape:groupmode="layer" inkscape:label="Page 1"
                    transform="matrix(1.3333333,0,0,-1.3333333,4113.0895,20811.289)">
                    <g id="g12" transform="scale(0.1)">
                        <path
                            d="m -29381.38,155324.85 c -196.826,0 -358.696,-147.62 -376.514,-343.32 -1.132,-12.49 8.044,-23.48 20.496,-24.79 12.693,-1.3 23.464,8.2 24.614,20.69 15.682,172.22 158.158,302.13 331.404,302.13 183.494,0 332.807,-149.3 332.807,-332.88 0,-12.49 10.139,-22.56 22.645,-22.56 12.507,0 22.646,10.07 22.646,22.56 0,208.56 -169.61,378.17 -378.098,378.17"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.86384px;"
                            id="path860" class="svg-elem-36"></path>
                        <path
                            d="m -29403.282,155413.85 h 45.318 v 113.33 l -0.604,157.1 h -45.299 l 0.585,-157.1 v -113.33"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.88589px;"
                            id="path864" class="svg-elem-37"></path>
                        <path
                            d="m -29117.075,155321.19 67.56,107.94 90.519,140.08 -38.151,24.44 -90.538,-140.08 -67.541,-108.12 38.151,-24.26"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.88033px;"
                            id="path868" class="svg-elem-38"></path>
                        <path
                            d="m -29641.309,155341.07 39.899,21.45 -30.356,56.44 -103.418,193.61 -39.901,-21.45 103.42,-193.42 30.356,-56.63"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.88149px;"
                            id="path872" class="svg-elem-39"></path>
                        <path
                            d="m -30054.726,155375.13 -23.553,-38.64 213.118,-129.38 h -0.01 l 54.81,-33.42 23.609,38.65 -54.819,33.41 -213.156,129.38"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.86692px;"
                            id="path876" class="svg-elem-40"></path>
                        <path
                            d="m -28843.917,155209.3 171.528,91.75 -21.147,40.1 -168.152,-89.89 -0.08,0.18 -129.457,-68.62 21.147,-40.09 126.082,66.76 0.07,-0.19"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.86484px;"
                            id="path880" class="svg-elem-41"></path>
                        <path d="m -28586.106,155152.89 -340.931,-69.87 9.081,-44.48 340.913,69.87 -9.063,44.48"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.85329px;"
                            id="path884" class="svg-elem-42"></path>
                        <path d="m -30179.984,155163.85 317.136,-103.97 13.941,43.07 -317.136,103.97 -13.941,-43.07"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.8566px;"
                            id="path888" class="svg-elem-43"></path>
                        <path
                            d="m -29751.746,155263.78 34.466,29.45 -147.911,174.05 h 0.02 l -41.611,48.95 -34.513,-29.44 41.608,-48.77 147.94,-174.24"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.87558px;"
                            id="path892" class="svg-elem-44"></path>
                        <path
                            d="m -29490.915,155407 -35.173,167.2 -19.229,96.14 -44.367,-9.24 16.591,-82.94 h -0.117 l 2.341,-11.12 0.426,-2.07 h 0.02 l 35.163,-167.21 44.347,9.24"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.88503px;"
                            id="path896" class="svg-elem-45"></path>
                        <path
                            d="m -29181.158,155556.47 25.932,94.61 -43.629,12.25 -27.515,-100.45 h 0.02 l -45.57,-164.71 43.591,-12.06 45.588,164.52 v 0 l 0.02,0.2 1.583,5.64 h -0.02"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.8846px;"
                            id="path900" class="svg-elem-46"></path>
                        <path
                            d="m -29030.675,155236.47 165.477,173.77 0.169,-0.19 52.166,56.61 -32.691,31.3 -50.385,-54.73 -0.09,0.19 -167.352,-175.64 32.71,-31.31"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.87446px;"
                            id="path904" class="svg-elem-47"></path>
                        <path
                            d="m -28589.382,154969.15 -304.526,48.53 c -0.993,0.19 -1.911,0 -2.885,0 -1.108,0 -2.178,0 -3.286,0 -2.082,-0.38 -4.05,-0.95 -5.941,-1.72 -0.554,-0.19 -1.108,-0.19 -1.643,-0.38 l -129.567,-65.34 h -105.801 c -3.554,0 -7.05,-0.96 -10.259,-2.48 l -206.31,-104.5 -106.036,100.67 c -5.771,5.54 -13.998,7.46 -21.655,5.35 l -75.545,-21.01 -160.912,71.64 c -2.997,1.34 -6.109,1.91 -9.195,1.91 l -57.843,94.95 c -4.109,6.88 -11.456,10.89 -19.345,10.89 h -78.783 c -1.788,0 -3.538,-0.19 -5.257,-0.76 -0.138,0 -0.264,0.19 -0.4,0 -0.04,0 -0.06,0 -0.08,0 -2.002,-0.58 -3.947,-1.34 -5.754,-2.3 l -697.694,-410.74 c -4,40.31 -6.079,81.19 -6.079,121.89 0,674.77 548.873,1223.64 1223.529,1223.64 674.676,0 1223.569,-548.87 1223.569,-1223.64 0,-35.92 -2.102,-72.22 -5.254,-108.13 l -418.714,258.29 c -2.522,1.71 -5.368,2.67 -8.33,3.24 z m -385.567,-104.31 h -122.346 c -5.215,0 -10.316,-1.71 -14.347,-5.16 l -142.482,-116.53 -70.572,67.06 187.053,94.75 h 105.82 c 3.534,0 7.03,0.77 10.182,2.3 l 80.43,40.69 z m 863.161,-49.09 c 0,699.8 -569.2,1268.92 -1268.865,1268.92 -699.626,0 -1268.824,-569.12 -1268.824,-1268.92 0,-54.07 3.45,-108.71 10.259,-162.01 0,-0.19 0.03,-0.19 0.03,-0.19 0.03,-0.19 0.192,-0.39 0.241,-0.77 0.446,-2.67 1.297,-5.16 2.582,-7.44 0.06,0 0.06,-0.2 0.117,-0.39 1.179,-1.91 2.667,-3.63 4.31,-5.16 0.399,-0.38 0.852,-0.57 1.278,-0.95 1.515,-1.15 3.131,-2.1 4.872,-2.87 0.628,-0.38 1.228,-0.57 1.875,-0.76 2.281,-0.77 4.631,-1.34 7.048,-1.34 0.04,0 0.07,0 0.1,0 0.01,0 0.02,0 0.03,0 0.01,0 0.01,0 0.02,0 0.01,0 0.02,0 0.04,0 0.919,0 1.866,0 2.812,0.19 0.36,0 0.631,0.19 0.976,0.38 2.448,0.38 4.857,1.15 7.147,2.3 0.144,0.19 0.32,0.19 0.463,0.19 0.01,0 0.03,0 0.04,0 l 701.927,413.42 12.567,-48.72 -74.685,-80.62 c -0.839,-0.95 -1.613,-1.91 -2.3,-3.06 l -176.815,-268.22 c -6.874,-10.51 -4.004,-24.65 6.458,-31.53 3.828,-2.48 8.159,-3.63 12.433,-3.63 7.366,0 14.569,3.63 18.928,10.13 l 175.802,266.89 81.8,88.26 c 5.25,5.73 7.262,13.57 5.317,21.02 l -15.874,61.52 h 36.814 l 113.831,-187.04 c 6.497,-10.7 20.457,-14.14 31.119,-7.64 10.685,6.5 14.088,20.44 7.583,31.14 l -23.1,38.02 119.631,-53.11 c 4.826,-2.3 10.2,-2.68 15.267,-1.15 l 71.011,19.68 216.71,-205.76 c 8.311,-7.83 21.073,-8.4 29.937,-1.14 l 151.69,124.18 h 129.472 c 9.227,0 17.518,5.54 20.996,14.14 l 55.46,136.4 282.308,-45.09 446.071,-275.29 c 0.134,0 0.287,0 0.421,-0.19 0.42,-0.19 0.917,-0.39 1.375,-0.58 2.083,-0.95 4.203,-1.72 6.4,-2.1 0.382,0 0.669,-0.19 1.07,-0.38 0.325,0 0.631,0.19 0.937,0.19 0.554,0 1.108,-0.19 1.662,-0.19 1.967,0 3.935,0.19 5.826,0.76 0.592,0.19 1.089,0.38 1.663,0.58 1.948,0.76 3.744,1.72 5.444,2.86 0.554,0.39 1.07,0.77 1.586,1.15 1.796,1.53 3.458,3.25 4.776,5.35 0.08,0.19 0.06,0.19 0.134,0.38 0.745,1.14 1.031,2.67 1.528,4.01 0.516,1.53 1.223,2.87 1.452,4.4 0.02,0.19 0.1,0.38 0.114,0.38 5.77,49.48 8.712,99.72 8.712,149.4"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.91045px;"
                            id="path1004" class="svg-elem-48"></path>
                        <path d="m -30848.172,154614.49 h 970.34 v 45.39 h -970.34 v -45.39"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.82304px;"
                            id="path1008" class="svg-elem-49"></path>
                        <path d="m -29777.385,154569.24 h 332.293 v 45.33 h -332.293 v -45.33"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.82026px;"
                            id="path1012" class="svg-elem-50"></path>
                        <path d="m -29159.449,154659.88 v -45.39 h 1245.521 v 45.39 h -1245.521"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.82304px;"
                            id="path1016" class="svg-elem-51"></path>
                        <path d="m -29238.314,154524.03 h 526.834 v 45.26 h -526.834 v -45.26"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.81749px;"
                            id="path1020" class="svg-elem-52"></path>
                        <path d="m -30180.602,154524.03 h 210.014 v 45.26 h -210.014 v -45.26"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.81749px;"
                            id="path1024" class="svg-elem-53"></path>
                        <path
                            d="m -30741.822,153958.52 h 52.08 c 14.637,0 27.089,5.23 37.348,15.69 10.266,10.47 15.37,22.74 15.37,37 v 52.15 c 0,34.65 -17.555,51.97 -52.718,51.97 h -52.08 z m 0,209.69 h 52.08 c 14.637,0 27.089,5.05 37.348,15.34 10.266,10.28 15.37,22.55 15.37,36.63 v 52.15 c 0,14.62 -5.104,27.07 -15.37,37.36 -10.259,10.28 -22.711,15.33 -37.348,15.33 h -52.08 z m -104.841,-261.85 v 470.82 h 209.639 c 28.462,0 52.952,-10.29 73.448,-31.04 20.504,-20.75 30.763,-45.29 30.763,-73.81 v -25.8 c 0,-30.86 -8.692,-55.04 -26.045,-72.37 -17.364,-17.5 -43.419,-28.15 -78.166,-32.3 34.747,0 60.802,-10.65 78.166,-31.76 17.353,-21.11 26.045,-45.47 26.045,-73.09 v -25.8 c 0,-28.51 -10.259,-53.05 -30.763,-73.81 -20.496,-20.57 -44.986,-31.04 -73.448,-31.04 h -209.639"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path908" class="svg-elem-54"></path>
                        <path
                            d="m -30412.303,153906.36 v 470.82 h 261.75 v -52.16 h -156.92 v -156.81 h 104.809 v -52.88 h -104.809 v -156.81 h 156.92 v -52.16 h -261.75"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path912" class="svg-elem-55"></path>
                        <path d="m -29858.051,153906.36 v 470.82 h 104.828 v -418.66 h 156.91 v -52.16 h -261.738"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path916" class="svg-elem-56"></path>
                        <path
                            d="m -29371.584,154272.33 v -261.12 c 0,-14.26 5.107,-26.53 15.357,-37 10.232,-10.46 22.503,-15.69 36.705,-15.69 14.653,0 27.105,5.23 37.373,15.69 10.25,10.47 15.358,22.74 15.358,37 v 261.12 c 0,14.62 -5.108,27.07 -15.358,37.36 -10.268,10.28 -22.72,15.33 -37.373,15.33 -14.202,0 -26.473,-5.05 -36.705,-15.33 -10.25,-10.29 -15.357,-22.74 -15.357,-37.36 z m 0,104.85 h 104.793 c 28.476,0 52.946,-10.29 73.464,-31.04 20.482,-20.75 30.768,-45.29 30.768,-73.81 v -261.12 c 0,-28.51 -10.286,-53.05 -30.768,-73.81 -20.518,-20.57 -44.988,-31.04 -73.464,-31.04 h -104.793 c -28.476,0 -53.073,10.29 -73.771,30.86 -20.717,20.4 -31.075,45.11 -31.075,73.99 v 261.12 c 0,28.88 10.358,53.6 31.075,73.99 20.698,20.57 45.295,30.86 73.771,30.86"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path920" class="svg-elem-57"></path>
                        <path
                            d="m -28728.231,154011.21 c -4.187,-69.84 -38.907,-104.85 -104.197,-104.85 h -104.828 c -28.476,0 -53.019,10.29 -73.754,30.86 -20.716,20.4 -31.093,45.11 -31.093,73.99 v 261.12 c 0,28.52 10.16,53.06 30.48,73.81 20.265,20.75 45.078,31.04 74.367,31.04 h 104.828 c 65.687,0 100.425,-35.01 104.197,-104.85 h -52.099 c -4.186,35.19 -21.564,52.69 -52.098,52.69 h -52.712 c -14.256,0 -26.473,-5.05 -36.723,-15.33 -10.268,-10.29 -15.393,-22.74 -15.393,-37.36 v -261.12 c 0,-14.26 5.125,-26.53 15.393,-37 10.25,-10.46 22.467,-15.69 36.723,-15.69 h 52.712 c 30.949,0 48.327,17.5 52.098,52.69 h 52.099"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path924" class="svg-elem-58"></path>
                        <path
                            d="m -28502.911,154168.21 h 104.847 v 104.12 c 0,14.62 -5.125,27.07 -15.393,37.36 -10.251,10.28 -22.702,15.33 -37.337,15.33 -14.238,0 -26.474,-5.05 -36.706,-15.33 -10.267,-10.29 -15.411,-22.74 -15.411,-37.36 z m -104.828,-261.85 v 365.97 c 0,28.88 10.376,53.6 31.075,73.99 20.734,20.57 45.295,30.86 73.753,30.86 h 104.847 c 28.422,0 52.91,-10.29 73.428,-31.04 20.5,-20.75 30.751,-45.29 30.751,-73.81 v -365.97 h -104.179 v 208.97 h -104.847 v -208.97 h -104.828"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path928" class="svg-elem-59"></path>
                        <path d="m -28173.375,153906.36 v 470.82 h 104.828 v -418.66 h 156.945 v -52.16 h -261.773"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.80459px;"
                            id="path932" class="svg-elem-60"></path>
                        <path d="m -30562.379,153696.14 h 20.477 v -98.02 h 61.305 v -18.5 h -81.782 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path936" class="svg-elem-61"></path>
                        <path
                            d="m -30337.435,153637.49 v 0.35 c 0,22.57 -16.503,41.44 -39.657,41.44 -23.156,0 -39.3,-18.52 -39.3,-41.08 v -0.36 c 0,-22.74 16.473,-41.42 39.629,-41.42 23.155,0 39.328,18.33 39.328,41.07 z m -100.457,0 v 0.35 c 0,32.8 25.33,60.3 61.129,60.3 35.826,0 60.802,-27.15 60.802,-59.94 v -0.36 c 0,-32.78 -25.321,-60.29 -61.131,-60.29 -35.811,0 -60.8,27.15 -60.8,59.94"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.76293px;"
                            id="path940" class="svg-elem-62"></path>
                        <path
                            d="m -30263.087,153637.49 v 0.35 c 0,33.15 24.836,60.3 60.133,60.3 21.501,0 34.485,-7.58 45.651,-18.16 l -13.157,-15.16 c -9.339,8.64 -19.337,14.46 -32.649,14.46 -22.16,0 -38.478,-18.34 -38.478,-41.08 v -0.36 c 0,-22.91 16.143,-41.42 38.478,-41.42 14.308,0 23.463,5.81 33.46,15.16 l 13.159,-13.4 c -12.135,-12.69 -25.476,-20.63 -47.305,-20.63 -33.963,0 -59.292,26.45 -59.292,59.94"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.76293px;"
                            id="path944" class="svg-elem-63"></path>
                        <path
                            d="m -30031.158,153625.76 -20.145,46.71 -19.995,-46.71 z m -29.3,71.22 h 18.977 l 51.308,-117.41 h -21.656 l -11.826,28.03 h -55.135 l -11.987,-28.03 h -20.991 l 51.31,117.41"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.76286px;"
                            id="path948" class="svg-elem-64"></path>
                        <path d="m -29936.98,153696.14 h 20.477 v -98.02 h 61.305 v -18.5 h -81.782 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path952" class="svg-elem-65"></path>
                        <path
                            d="m -29717.421,153696.14 h 86.458 v -18.33 h -65.974 v -30.33 h 58.472 v -18.33 h -58.472 v -31.2 h 66.787 v -18.33 h -87.271 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path956" class="svg-elem-66"></path>
                        <path
                            d="m -29473.976,153696.14 -40.65,-56.94 42.307,-59.58 h -24.15 l -30.814,44.42 -30.638,-44.42 h -23.48 l 42.131,59.22 -40.474,57.3 h 24.15 l 28.963,-42.31 29.157,42.31 h 23.498"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path960" class="svg-elem-67"></path>
                        <path
                            d="m -29373.655,153635.49 c 15.513,0 25.155,8.64 25.155,20.8 v 0.36 c 0,13.75 -9.818,20.8 -25.155,20.8 h -23.815 v -41.96 z m -44.299,60.65 h 45.974 c 27.323,0 44.299,-15.52 44.299,-38.96 v -0.36 c 0,-26.08 -20.977,-39.83 -46.626,-39.83 h -23.163 v -37.37 h -20.484 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path964" class="svg-elem-68"></path>
                        <path
                            d="m -29273.457,153696.14 h 86.448 v -18.33 h -65.982 v -30.33 h 58.49 v -18.33 h -58.49 v -31.2 h 66.81 v -18.33 h -87.276 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path968" class="svg-elem-69"></path>
                        <path
                            d="m -29078.156,153638.31 c 14.649,0 23.974,7.76 23.974,19.57 v 0.35 c 0,12.35 -8.99,19.22 -24.15,19.22 h -29.809 v -39.14 z m -50.469,57.83 h 51.967 c 14.631,0 26.143,-4.41 33.652,-11.64 6.17,-6.35 9.66,-14.98 9.66,-25.21 v -0.35 c 0,-19.04 -11.51,-30.49 -27.676,-35.25 l 31.502,-44.07 h -24.344 l -28.628,40.54 h -25.649 v -40.54 h -20.484 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path972" class="svg-elem-70"></path>
                        <path d="m -28973.815,153696.14 h 20.483 v -116.52 h -20.483 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path976" class="svg-elem-71"></path>
                        <path
                            d="m -28888.937,153696.14 h 86.448 v -18.33 h -65.964 v -30.33 h 58.472 v -18.33 h -58.472 v -31.2 h 66.81 v -18.33 h -87.294 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path980" class="svg-elem-72"></path>
                        <path
                            d="m -28744.087,153696.14 h 18.967 l 62.492,-80.57 v 80.57 h 20.131 v -116.52 h -17.169 l -64.29,82.85 v -82.85 h -20.131 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path984" class="svg-elem-73"></path>
                        <path
                            d="m -28584.484,153637.49 v 0.35 c 0,33.15 24.822,60.3 60.134,60.3 21.49,0 34.483,-7.58 45.659,-18.16 l -13.169,-15.16 c -9.343,8.64 -19.356,14.46 -32.649,14.46 -22.16,0 -38.484,-18.34 -38.484,-41.08 v -0.36 c 0,-22.91 16.148,-41.42 38.484,-41.42 14.315,0 23.465,5.81 33.461,15.16 l 13.169,-13.4 c -12.147,-12.69 -25.492,-20.63 -47.335,-20.63 -33.954,0 -59.27,26.45 -59.27,59.94"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.76293px;"
                            id="path988" class="svg-elem-74"></path>
                        <path
                            d="m -28423.168,153696.14 h 86.43 v -18.33 h -65.965 v -30.33 h 58.49 v -18.33 h -58.49 v -31.2 h 66.811 v -18.33 h -87.276 v 116.52"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.7628px;"
                            id="path992" class="svg-elem-75"></path>
                        <path
                            d="m -28286.164,153596.59 12.323,14.64 c 11.159,-9.7 22.494,-15.17 36.827,-15.17 12.64,0 20.626,6 20.626,14.64 v 0.35 c 0,8.28 -4.654,12.87 -26.302,17.81 -24.822,5.99 -38.802,13.39 -38.802,34.72 v 0.35 c 0,20.1 16.66,33.86 39.806,33.86 16.977,0 30.463,-5.12 42.31,-14.64 l -11,-15.51 c -10.507,7.76 -20.979,11.98 -31.662,11.98 -11.988,0 -18.987,-6.16 -18.987,-13.75 v -0.35 c 0,-8.99 5.342,-13.04 27.819,-18.33 24.645,-6 37.303,-14.81 37.303,-34.2 v -0.36 c 0,-21.86 -17.135,-34.72 -41.64,-34.72 -17.805,0 -34.641,6.17 -48.621,18.68"
                            style="fill: rgb(4, 6, 6); fill-opacity: 1; fill-rule: nonzero; stroke: none; stroke-width: 1.76291px;"
                            id="path996" class="svg-elem-76"></path>
                    </g>
                </g>
            </svg>



        </div>
    </div>
</body>



</html>


<script>
    var script = document.createElement('script');
    script.src = "{{mix('js/app.js')}}";
    setTimeout(() => {
        document.getElementById('index').append(script);
    }, 0);
    // 4300
</script>