export const types = {
    FETCH_RESERVATIONS: 'FETCH_RESERVATIONS',
    FETCH_RESERVATION: 'FETCH_RESERVATION',
    DELETE_RESERVATION: 'DELETE_RESERVATION',
    UPDATE_RESERVATION: 'UPDATE_RESERVATION',
    CREATE_RESERVATION: 'CREATE_RESERVATION',
    CREATE_EXTERNAL_RESERVATION: 'CREATE_EXTERNAL_RESERVATION',
    FETCH_DISABLED_DATES: 'FETCH_DISABLED_DATES',
    BLOCK_RESERVATION_DATE: 'BLOCK_RESERVATION_DATE',
    UPDATE_VISIBILITY: 'UPDATE_VISIBILITY'
};