export const types = {
    FETCH_NEWSLETTERS: 'FETCH_NEWSLETTERS',
    FETCH_NEWSLETTER: 'FETCH_NEWSLETTER',
    DELETE_NEWSLETTER: 'DELETE_NEWSLETTER',
    UPDATE_NEWSLETTER: 'UPDATE_NEWSLETTER',
    CREATE_NEWSLETTER: 'CREATE_NEWSLETTER',
    RESET_NEWSLETTER: 'RESET_NEWSLETTER',
    UPDATE_NEWSLETTER_SUBSCRIPTION: 'UPDATE_NEWSLETTER_SUBSCRIPTION',
};