export const types = {
    FETCH_COUPONS: 'FETCH_COUPONS',
    FETCH_COUPON: 'FETCH_COUPON',
    DELETE_COUPON: 'DELETE_COUPON',
    UPDATE_COUPON: 'UPDATE_COUPON',
    CREATE_COUPON: 'CREATE_COUPON',
    RESET_COUPON: 'RESET_COUPON'
};