export const types = {
    FETCH_EXPERIENCES: 'FETCH_EXPERIENCES',
    FETCH_EXPERIENCE: 'FETCH_EXPERIENCE',
    DELETE_EXPERIENCE: 'DELETE_EXPERIENCE',
    UPDATE_EXPERIENCE: 'UPDATE_EXPERIENCE',
    CREATE_EXPERIENCE: 'CREATE_EXPERIENCE',
};