export const types = {
    FETCH_TRANSFERS: 'FETCH_TRANSFERS',
    FETCH_TRANSFER: 'FETCH_TRANSFER',
    DELETE_TRANSFER: 'DELETE_TRANSFER',
    UPDATE_TRANSFER: 'UPDATE_TRANSFER',
    CREATE_TRANSFER: 'CREATE_TRANSFER',
    CREATE_EXTERNAL_TRANSFER: 'CREATE_EXTERNAL_TRANSFER',
    FETCH_DISABLED_DATES: 'FETCH_DISABLED_DATES',
    BLOCK_TRANSFER_DATE: 'BLOCK_TRANSFER_DATE',
    UPDATE_VISIBILITY: 'UPDATE_VISIBILITY'
};